import React, { useState, useMemo } from 'react';
import axios from 'axios';
import { Play, AlertTriangle, CheckCircle, Shield, Globe, FileText, Info, BarChart2, PieChart as PieIcon, Download } from 'lucide-react';
import { PieChart, Pie, Cell, Tooltip, BarChart, Bar, XAxis, YAxis, CartesianGrid, ResponsiveContainer } from 'recharts';
import jsPDF from 'jspdf';
// 1. CHANGED IMPORT HERE:
import autoTable from 'jspdf-autotable';

function Dashboard({ refreshHistory, userEmail, history }) { 
  const [scanType, setScanType] = useState('text');
  const [inputData, setInputData] = useState('');
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);

  // --- 1. CALCULATE REAL-TIME STATS ---
  const stats = useMemo(() => {
    if (!history || history.length === 0) return { safe: 0, risky: 0, types: [], pieData: [], barData: [], total: 0 };
    
    const safeCount = history.filter(h => h.score >= 70).length;
    const riskyCount = history.length - safeCount;
    
    const pieData = [
      { name: 'Safe', value: safeCount, color: '#10b981' },
      { name: 'Risky', value: riskyCount, color: '#ef4444' }
    ];

    const typeCounts = { text: 0, url: 0, job: 0 };
    history.forEach(h => {
      if (typeCounts[h.type] !== undefined) typeCounts[h.type]++;
    });
    const barData = [
      { name: 'Text', count: typeCounts.text },
      { name: 'URL', count: typeCounts.url },
      { name: 'Job', count: typeCounts.job }
    ];

    return { pieData, barData, total: history.length };
  }, [history]);

  // --- 2. GENERATE PDF FUNCTION ---
  const generatePDF = () => {
    const doc = new jsPDF();
    const date = new Date().toLocaleString();

    // Header & Branding
    doc.setFillColor(15, 23, 42); 
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.text("VeriCheck", 14, 20); 
    doc.setFontSize(10);
    doc.text("Threat Intelligence Report", 14, 28);
    doc.text(`Generated: ${date}`, 140, 28);

    // Verdict Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(16);
    doc.text("Investigation Results", 14, 55);

    doc.setFontSize(12);
    doc.text(`Verdict: ${result.verdict}`, 14, 65);
    doc.text(`Trust Score: ${result.score}/100`, 14, 72);
    doc.text(`Scan Type: ${scanType.toUpperCase()}`, 100, 65);

    // 2. CHANGED TABLE CALL HERE:
    autoTable(doc, {
      startY: 80,
      head: [['Metric', 'Score', 'Status']],
      body: [
        ['Language Quality', `${result.breakdown.language}%`, result.breakdown.language > 50 ? 'Pass' : 'Low Quality'],
        ['Source Credibility', `${result.breakdown.source}%`, result.breakdown.source > 50 ? 'Trusted' : 'Unknown/Risky'],
        ['Risk Factors', `${result.breakdown.risk}%`, result.breakdown.risk > 50 ? 'Critical' : 'Low'],
      ],
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246] } 
    });

    // Details & Flags
    let finalY = doc.lastAutoTable.finalY + 10;
    doc.setFontSize(14);
    doc.text("AI Analysis", 14, finalY);
    
    doc.setFontSize(10);
    doc.setTextColor(100);
    const splitText = doc.splitTextToSize(result.explanation, 180);
    doc.text(splitText, 14, finalY + 8);

    if (result.flags && result.flags.length > 0) {
      doc.setTextColor(239, 68, 68); 
      doc.text(`Flags Detected: ${result.flags.join(", ")}`, 14, finalY + 20);
    }

    // Evidence
    doc.setTextColor(0,0,0);
    doc.text("Evidence / Input Data:", 14, finalY + 35);
    doc.setFont("courier");
    const snippet = inputData.length > 500 ? inputData.substring(0, 500) + "..." : inputData;
    const splitSnippet = doc.splitTextToSize(snippet, 180);
    doc.text(splitSnippet, 14, finalY + 42);

    // Footer
    doc.setFont("helvetica", "italic");
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Report generated by VeriCheck for user: ${userEmail}`, 14, 280);

    doc.save(`VeriCheck_Report_${Date.now()}.pdf`);
  };

  const handleVerify = async () => {
    if(!inputData) return;
    setLoading(true);
    setResult(null);
    try {
      const response = await axios.post('http://localhost:5000/api/analyze', {
        type: scanType,
        data: inputData,
        email: userEmail
      });
      setResult(response.data);
      refreshHistory(); 
    } catch (err) { alert("Analysis Failed"); } 
    finally { setLoading(false); }
  };

  const renderHighlightedText = (text, flags) => {
    if (!flags || flags.length === 0) return text;
    const regex = new RegExp(`(${flags.join('|')})`, 'gi');
    const parts = text.split(regex);
    return parts.map((part, i) => 
      flags.some(flag => part.toLowerCase() === flag.toLowerCase()) ? 
        <mark key={i} style={{backgroundColor: 'rgba(239, 68, 68, 0.3)', color: '#fff', padding: '2px 4px', borderRadius: '4px'}}>{part}</mark> : part
    );
  };

  const getScoreColor = (score) => {
    if (score >= 80) return '#10b981';
    if (score >= 50) return '#f59e0b';
    return '#ef4444';
  };

  return (
    <div style={{display: 'flex', flexDirection: 'column', gap: '2rem'}}>
      
      {/* TOP SECTION: LIVE ANALYTICS */}
      <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '1.5rem'}}>
        
        {/* STAT CARD 1 */}
        <div className="stat-card">
          <h4 style={{margin:0, color:'#94a3b8', display:'flex', alignItems:'center', gap:'8px'}}><BarChart2 size={16}/> Total Scans</h4>
          <div style={{fontSize:'2.5rem', fontWeight:'bold', color:'white', marginTop:'10px'}}>{stats.total || 0}</div>
          <div style={{fontSize:'0.8rem', color:'#64748b'}}>Lifetime checks performed</div>
        </div>

        {/* STAT CARD 2 */}
        <div className="stat-card" style={{display:'flex', alignItems:'center', justifyContent:'space-between'}}>
          <div>
            <h4 style={{margin:0, color:'#94a3b8', display:'flex', alignItems:'center', gap:'8px'}}><PieIcon size={16}/> Threat Ratio</h4>
            <div style={{marginTop:'10px'}}>
              <div style={{color:'#ef4444', fontWeight:'bold'}}>{stats.pieData[1] ? stats.pieData[1].value : 0} Threats</div>
              <div style={{color:'#10b981', fontWeight:'bold'}}>{stats.pieData[0] ? stats.pieData[0].value : 0} Safe</div>
            </div>
          </div>
          <div style={{width: 80, height: 80}}>
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie data={stats.pieData} innerRadius={25} outerRadius={40} paddingAngle={5} dataKey="value">
                  {stats.pieData && stats.pieData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* STAT CARD 3 */}
        <div className="stat-card">
          <h4 style={{margin:0, color:'#94a3b8', marginBottom:'10px'}}>Scan Activity</h4>
          <div style={{width: '100%', height: 60}}>
             <ResponsiveContainer width="100%" height="100%">
               <BarChart data={stats.barData}>
                 <Bar dataKey="count" fill="#22d3ee" radius={[4, 4, 0, 0]} barSize={40} />
               </BarChart>
             </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* BOTTOM SECTION: ANALYSIS TOOL */}
      <div className="analysis-panel">
        <h2 style={{marginTop:0, fontSize:'1.2rem', marginBottom:'1.5rem', display:'flex', alignItems:'center', gap:'10px'}}>
          <Shield size={24} color="#3b82f6"/> New Investigation
        </h2>
        
        <div style={{display:'flex', gap:'1rem', marginBottom:'1.5rem', borderBottom:'1px solid #334155', paddingBottom:'1rem'}}>
           <button onClick={() => setScanType('text')} style={tabStyle(scanType === 'text')}><FileText size={16}/> Text Analysis</button>
           <button onClick={() => setScanType('url')} style={tabStyle(scanType === 'url')}><Globe size={16}/> URL Inspector</button>
           <button onClick={() => setScanType('job')} style={tabStyle(scanType === 'job')}><BriefcaseIcon/ > Job Fraud</button>
        </div>

        <div className="input-section">
          {scanType === 'url' ? (
             <input type="text" placeholder="Enter URL (e.g., http://suspicious-site.com)..." value={inputData} onChange={(e) => setInputData(e.target.value)} />
          ) : (
             <textarea rows="6" placeholder="Paste email content, SMS, or job description here..." value={inputData} onChange={(e) => setInputData(e.target.value)} />
          )}
          
          <div className="action-bar">
            <button className="primary-btn" onClick={handleVerify} disabled={loading}>
              {loading ? 'Analyzing...' : <><Play size={16}/> Run Analysis</>}
            </button>
          </div>
        </div>

        {result && (
          <div style={{marginTop: '2rem', animation: 'fadeIn 0.5s ease'}}>
            
            <div className="result-alert" style={{
              backgroundColor: result.score > 70 ? 'rgba(16, 185, 129, 0.1)' : 'rgba(239, 68, 68, 0.1)',
              border: `1px solid ${getScoreColor(result.score)}`
            }}>
               {result.score > 70 ? <CheckCircle color="#10b981" size={32}/> : <AlertTriangle color="#ef4444" size={32}/>}
               <div style={{width: '100%'}}>
                 <div style={{display:'flex', justifyContent:'space-between', alignItems:'center'}}>
                   <strong style={{color: getScoreColor(result.score), fontSize: '1.2rem', textTransform:'uppercase'}}>{result.verdict}</strong>
                   
                   {/* DOWNLOAD BUTTON */}
                   <button onClick={generatePDF} style={{
                     background:'transparent', border:'1px solid #475569', color:'white', 
                     padding:'6px 12px', borderRadius:'6px', cursor:'pointer', display:'flex', gap:'8px', alignItems:'center', fontSize:'0.9rem'
                   }}>
                     <Download size={16}/> Download Report
                   </button>

                 </div>
                 <div style={{marginTop:'5px', color: '#cbd5e1', fontSize:'1rem'}}>{result.explanation}</div>
               </div>
            </div>

            <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '1rem', marginTop: '1.5rem'}}>
              <ScoreCard title="Language Quality" score={result.breakdown.language} icon={<FileText size={16}/>} />
              <ScoreCard title="Source Trust" score={result.breakdown.source} icon={<Globe size={16}/>} />
              <ScoreCard title="Risk Factors" score={result.breakdown.risk} icon={<AlertTriangle size={16}/>} inverse={true} />
            </div>

            {scanType !== 'url' && (
              <div style={{marginTop: '1.5rem', background: '#0f172a', padding: '1.5rem', borderRadius: '8px', border: '1px solid #334155'}}>
                <h4 style={{marginTop:0, color:'#94a3b8', display:'flex', alignItems:'center', gap:'8px'}}>
                  <Info size={16}/> Threat Detection Highlights
                </h4>
                <p style={{lineHeight: '1.8', color: '#e2e8f0'}}>
                  {renderHighlightedText(inputData, result.flags)}
                </p>
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}

const ScoreCard = ({ title, score, icon, inverse = false }) => {
  const displayScore = inverse ? score : score; 
  const color = inverse 
    ? (score > 50 ? '#ef4444' : '#10b981') 
    : (score > 50 ? '#10b981' : '#ef4444');

  return (
    <div style={{background: '#1e293b', padding: '1rem', borderRadius: '8px', border: '1px solid #334155'}}>
      <div style={{display:'flex', justifyContent:'space-between', marginBottom:'8px', color:'#94a3b8', fontSize:'0.9rem'}}>
        <span style={{display:'flex', gap:'6px', alignItems:'center'}}>{icon} {title}</span>
        <span style={{color: color, fontWeight:'bold'}}>{displayScore}%</span>
      </div>
      <div style={{width:'100%', height:'6px', background:'#0f172a', borderRadius:'3px'}}>
        <div style={{width: `${displayScore}%`, height:'100%', background: color, borderRadius:'3px', transition:'width 1s ease'}}></div>
      </div>
    </div>
  );
};

const tabStyle = (active) => ({
  background: active ? '#334155' : 'transparent', 
  border:'none', color: active ? 'white' : '#94a3b8', padding:'8px 16px', borderRadius:'6px', 
  cursor:'pointer', display:'flex', alignItems:'center', gap:'8px', transition: 'all 0.2s'
});

const BriefcaseIcon = () => (
  <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"></rect><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"></path></svg>
);

export default Dashboard;